### ISSUE TITLE
Method not found

### ISSUE THREAD

**Issue by freiyer** [egeloen/IvoryGoogleMapBundle#100]
Just practicing with the documentation.

Every Ivory services works fine for me except the geocoding one. Just copy/paste the code from the doc : 

$map = $this->get('ivory_google_map.map');

$geocoder = $this->get('ivory_google_map.geocoder');
        $response = $geocoder->geocode('An address, City, FR');

```
    foreach($response->getResults() as $result)
    {
        // Request the google map merker service
        $marker2 = $this->get('ivory_google_map.marker');

        // Position the marker
        $marker2->setPosition($result->getGeometry()->getLocation());

        // Add the marker to the map
        $map->addMarker($marker2);
    }
```

getResults(), getGeometry() and getLocation() are not found.

Here is my config.yml : 

geocoder:
        # Enable the service
        enabled: true

```
    # Geocoder class
    class: "Ivory\GoogleMap\Services\Geocoding\Geocoder"
    provider:
        # Fake IP
        # If you set a fake IP, the parameter will replace the REMOTE_ADDR value by the given one
        #fake_ip: "123.345.567.123"

        # Provider class
        class: "Ivory\GoogleMap\Services\Geocoding\\Provider"

        # API key used by the provider
        # If you set an API key, this paremeter will be the second parameter provider constructor
        # By default, there is no api key ^_^
        #api_key: "apikey"

        # Locale used by the provider
        # If your set a locale, this parameter will be the second parameter provider constructor if there is no api key else it will be the third
        # By default, there is no locale
        locale: "fr"
```
