### ISSUE TITLE
Directions service

### ISSUE THREAD

**Issue by alexbaciu** [egeloen/IvoryGoogleMapBundle#118]
Hello, 

When I am trying to make a directions request I receive the following error:

ContextErrorException: Warning: json_decode() expects parameter 1 to be string, object given in /var/www/...../Symfony/vendor/egeloen/google-map/src/Ivory/GoogleMap/Services/Directions/Directions.php line 202

The code that I'm using is below:

  $this->get("ivory_google_map.directions")->route($address1, $address2);

The configuration looks like this:

  ivory_google_map:

```
directions:
    # Enable the service
    enabled: true

    # Your own directions class
    #class: "My\Fucking\Directions"

    # The http adapter
    adapter: "widop_http_adapter.curl"

    # The Directions API URL
    url: "http://maps.googleapis.com/maps/api/directions"

    # TRUE if the service uses HTTPS else FALSE
    https: false

    # The format used (json or xml)
    format: "json"

directions_request:
    # Your own directions request class
    #class: "My\Fucking\DirectionsRequest"

    # TRUE if the directions should avoid highways else FALSE
    # By default there is no avoid highways.
    avoid_highways: false

    # TRUE if the directions should avoid tolls else FALSE
    # By default there is no avoid tolls.
    avoid_tolls: false

    # TRUE if the directions should optimize waypoints.
    # By default there is no optimize waypoints.
    optimize_waypoints: false

    # TRUE if the directions should provide route alternatives.
    # By default there is no route alternatives.
    provide_route_alternatives: false

    # The region used to filter the directions results.
    # By default there is no region.
    region: "us"

    # The language used for this request.
    # By default there is no language.
    language: "en"

    # The travel mode used to filter directions results.
    # By default there is no travel mode.
    travel_mode: "DRIVING"

    # The unit system used.
    # By default there is no unit system.
    unit_system: "METRIC"

    # Indicates whether or not the directions request comes from a device with a location sensor
    # By default, the sensor is false
    sensor: false  
```

Have any idea?
Thank you,
Alex
