### ISSUE TITLE
Geocoder Locale is not working

### ISSUE THREAD

**Issue by soerenmartius** [egeloen/IvoryGoogleMapBundle#133]
Hi,

When i set the locale for geocoder in the config:
```

ivory_google_map:
    geocoder:
        enabled: true
        class: "Ivory\GoogleMap\Services\Geocoding\Geocoder"
        provider:
            class: "Ivory\GoogleMap\Services\Geocoding\GeocoderProvider"
            locale: "de"
            api_key: "foo"
    map:
        async: true
```
It won't work. The Geocoder always returns english formatted results.
