### ISSUE TITLE
Setup httplug.

### ISSUE THREAD

**Issue by xorgxx** [egeloen/IvoryGoogleMapBundle#213]
Hi i try to install, all is good but when i try to setup 
```
    httplug:
        classes:
            client: Http\Adapter\Guzzle6\Client
            message_factory: Http\Message\MessageFactory\GuzzleMessageFactory
        clients:
            acme:
                factory: httplug.factory.guzzle6 
```
my config : 
```
ivory_google_map:
    geocoder:
        client: httplug.client.default
        message_factory: httplug.message_factory.default
        format: json
        api_key: AIzaSyBN7P7TY.......
```
i get this error :
```
Fatal error: Uncaught exception 'Symfony\Component\DependencyInjection\Exception\RuntimeException' with message 'The definition for "httplug" has no class. If you intend to inject this service dynamically at runtime, please mark it as synthetic=true. If this is an abstract definition solely used by child definitions, please add abstract=true, otherwise specify a class to get rid of this error.' in 
```
Ps: Windows 10 64, php 5.6.25.

**Comment by xorgxx** [comment]
OK!! sorry i find my problem. it was that i set as service : 
```
    httplug:
        classes:
            client: Http\Adapter\Guzzle6\Client
            message_factory: Http\Message\MessageFactory\GuzzleMessageFactory
        clients:
            acme:
                factory: httplug.factory.guzzle6 
```
:/
